os: linux
dist: trusty
language: r
before_install:
    - tlmgr install latexmk
    - tlmgr install texliveonfly
script:
  - texliveonfly main.tex
  - make -B
  - mkdir -p site
  - mv main.pdf site/classes.pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/
  on:
    branch: master
